name: Python CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install pytest sphinx  

    - name: Run tests with pytest
      run: pytest  

  docs:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  

    - name: Install Sphinx
      run: pip install sphinx  

    - name: Ensure index.rst exists
      run: |
        cd Downloads/scanner/scanner_project/config  
        if [ ! -f index.rst ]; then
          echo "index.rst manquant, création automatique..."
          echo -e ".. Suivi Reseau Documentation\n\nWelcome to Suivi Reseau's documentation!\n" > index.rst
        fi

    - name: Build Sphinx docs
      run: |
        cd Downloads/scanner/scanner_project/config  
        make html  
