name: Python CI

on:
  push:
    branches:
      - main  # Le workflow s'exécute sur chaque push sur la branche principale
  pull_request:
    branches:
      - main  # S'exécute aussi lors des PRs vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise une image Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clone ton repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Utilise la version 3.9 de Python (ajuste selon tes besoins)

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests with pytest
      run: |
        pytest  # Lance pytest pour exécuter les tests unitaires

  docs:
    runs-on: ubuntu-latest  # Utilise une image Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clone ton repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Utilise la version 3.9 de Python (ajuste selon tes besoins)

    - name: Build Sphinx docs
      run: |
        cd docs  # Va dans le dossier contenant les fichiers Sphinx
        make html  # Génère la documentation en HTML

    - name: Upload documentation as artifact
      uses: actions/upload-artifact@v2
      with:
        name: sphinx-docs
        path: docs/_build/html  # Télécharge la documentation générée
